### ISSUE TITLE
failure of archiving a manually restarted project

### ISSUE THREAD

**Issue by ChristopheLegendre** [tgen/phoenix#206]
We need a way to **manually** archive a project that got restarted after a failure.

- If there is no failure in the first place, the project is correctly archived.
- If there is failure, the project is restarted using jetstream but if the project completes successfully, then the project is not archived.

### we need to add a way of manually start the archiving of a completed project after its manual restart.

note: might be an issue to add to jetstream_centro as well.

**Comment by PedalheadPHX** [comment]
we now have a script that will read the project YAML and copy to expected location, still a manual user intervention, copy is centro issue that will require other changes.
