### ISSUE TITLE
Need to rewrite so flagstat is generated by library

### ISSUE THREAD

**Issue by awchrist** [tgen/phoenix#226]
https://github.com/tgen/phoenix/blob/ee16c34ba9e9ac2851bef44aa1f54492d484f37d/modules/qc/bam_qc_all.jst#L79-L104

We need to split the flagstat step out by library to accurately track stats. 
Need to look into what additional command may be required to accomplish this.
If there are no native options we may need to split the bam and pipe into flagstats.

**Comment by PedalheadPHX** [comment]
suggest deleting from QC modules as it is redundant with `samtools stats`

**Comment by PedalheadPHX** [comment]
Putting on the v0.6 project so we can summarize the status on the project review
