### ISSUE TITLE
Samtools merge potentially generating an incomplete bam

### ISSUE THREAD

**Issue by bryce-turner** [tgen/phoenix#276]
https://github.com/tgen/phoenix/blob/d2dba1a151d00312a74abaed9f47596573329c33/modules/dna_alignment/bwa_mem_samtools.jst#L136-L158

If one of the bams are truncated, with or without the trailing '\' at the end of the samtools merge command. Then set -eu will still work, e.g. the job fails, but the bam is still created by samtools. This bam is not completed and does not pass samtools quickcheck as it is missing the EOF block.

**Comment by PedalheadPHX** [comment]
Improved our ability to diagnose by moving RM to separate task
