### ISSUE TITLE
Modularize Star Fusion

### ISSUE THREAD

**Issue by snasser** [tgen/phoenix#291]
Break down star fusion :FusionFilter/Annotator scripts and alignment scripts into separate modules to manage resources better.

Update Star Fusion annotation filter to include known fusion genes such as MAP3K14.
Either add all NSD2 fusions to AnnotationFilter.pm or add all miRNA with IgLocus to AnnotationFilter.pm which would pass all IG-NSD2 fusions.

**Comment by PedalheadPHX** [comment]
This is largely done by @bryce-turner
