### ISSUE TITLE
Need one more file for ichorCNA

### ISSUE THREAD

**Issue by awchrist** [tgen/phoenix#297]
https://github.com/tgen/phoenix/blob/6fd8bf55db44a80391a1bd859e11b997266a2e5f/modules/constitutional/ichorcna.jst#L94

need to add the igv compatible seg file that does not have the ".cna." in the name.
```
mv "{{ temp_dir }}/{{ sample.name }}.{{ aligner }}.ichorCNA.seg" "{{ results_dir }}/"
```

**Comment by bryce-turner** [comment]
Added in release v0.5.0, specific commit 29e9173
