### ISSUE TITLE
Add RG support for Bowtie2

### ISSUE THREAD

**Issue by PedalheadPHX** [tgen/phoenix#303]
https://github.com/tgen/phoenix/blob/75e245b7bff08e958b8989496854a7c2b6f0cbce/modules/dna_alignment/bowtie2_samtools.jst#L112-L125

Need to enable:

--rg-id <text> | Set the read group ID to <text>. This causes the SAM @RG header line to be printed, with <text> as the value associated with the ID: tag. It also causes the RG:Z: extra field to be attached to each SAM output record, with value set to <text>.
-- | --
--rg <text> | Add <text> (usually of the form TAG:VAL, e.g. SM:Pool1) as a field on the @RG header line. Note: in order for the @RG line to appear, --rg-id must also be specified. This is because the ID tag is required by the SAM Spec. Specify --rg multiple times to set multiple fields. See the SAM Spec for details about what fields are legal.

**Comment by bryce-turner** [comment]
Resolved with commit 2c71f2d
