### ISSUE TITLE
Star-Fusion BAM to CRAM fails

### ISSUE THREAD

**Issue by bryce-turner** [tgen/phoenix#310]
bam_to_cram for star-fusion fails after resolving the indexing errors in issue #306.
This likely was not known of before fixing the index issue since this step would not have been able to run before fixing that issue.

Now we have:
```
[E::cram_get_ref] Failed to populate reference for id 25
[main_samview] failed to write the SAM header
```

This appears to be because the star-fusion bam is made using GRCh38_gencode_v32_CTAT_lib_Dec062019. However for bam_to_cram we use GRCh38tgen_decoy.fa as the reference, which is what we use for the regular STAR alignment processes.

Needs further investigation.

**Comment by PedalheadPHX** [comment]
okay, we might want to look at moving away from the plug and play to downloading the source files, swapping in our reference genome and GTF then building the required files

**Comment by PedalheadPHX** [comment]
Source errors occur when trying to use the ensembl GTF as unlike gencode they only put genes in the PAR regions on chrX and chrY on chrX.

`* Running CMD: /packages/easybuild/software/STAR-Fusion/1.8.1-GCC-8.2.0-2.31.1-Perl-5.28.1-Python-3.7.2/ctat-genome-lib-builder/util/add_gtf_custom_targets.pl --in_gtf /scratch/jkeats/sf_testing/phoenix_test/Homo_sapiens.GRCh38.98.ucsc.gtf.revised.gtf --out_gtf /scratch/jkeats/sf_testing/phoenix_test/Homo_sapiens.GRCh38.98.ucsc.gtf.revised.custom.gtf
-add_gtf_custom_targets: parsing gtf file: /scratch/jkeats/sf_testing/phoenix_test/Homo_sapiens.GRCh38.98.ucsc.gtf.revised.gtf
-add_gtf_custom_targets: getting gene span info.
-adding custom CRLF2 entry
-adding custom CRLF2 entry (Y-allele)
Error, cannot find gene struct for chrY:CRLF2 based on /scratch/jkeats/sf_testing/phoenix_test/Homo_sapiens.GRCh38.98.ucsc.gtf.revised.gtf at /packages/easybuild/software/STAR-Fusion/1.8.1-GCC-8.2.0-2.31.1-Perl-5.28.1-Python-3.7.2/ctat-genome-lib-builder/util/add_gtf_custom_targets.pl line 93.
Error, cmd: /packages/easybuild/software/STAR-Fusion/1.8.1-GCC-8.2.0-2.31.1-Perl-5.28.1-Python-3.7.2/ctat-genome-lib-builder/util/add_gtf_custom_targets.pl --in_gtf /scratch/jkeats/sf_testing/phoenix_test/Homo_sapiens.GRCh38.98.ucsc.gtf.revised.gtf --out_gtf /scratch/jkeats/sf_testing/phoenix_test/Homo_sapiens.GRCh38.98.ucsc.gtf.revised.custom.gtf died with ret 6400 No such file or directory at /packages/easybuild/software/STAR-Fusion/1.8.1-GCC-8.2.0-2.31.1-Perl-5.28.1-Python-3.7.2/ctat-genome-lib-builder/lib/Pipeliner.pm line 186.
	Pipeliner::run(Pipeliner=HASH(0x730910)) called at /packages/easybuild/software/STAR-Fusion/1.8.1-GCC-8.2.0-2.31.1-Perl-5.28.1-Python-3.7.2/ctat-genome-lib-builder/prep_genome_lib.pl line 451
`

**Comment by PedalheadPHX** [comment]
Test build with our RNA refGenome and Gencode32 GTF completed, needs a starFusion test run
