### ISSUE TITLE
Need to add copy number vcf support

### ISSUE THREAD

**Issue by bryce-turner** [tgen/phoenix#326]

**Comment by tizatt** [comment]
This is the current vcf header for the build37 cnv files:

##INFO=<ID=IMPRECISE,Number=0,Type=Flag,Description="Imprecise structural variation">
##INFO=<ID=**END**,Number=1,Type=Integer,Description="End position of the variant described in this record">
##INFO=<ID=**SVLEN**,Number=.,Type=Integer,Description="Length between POS and END">
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
##INFO=<ID=**LOG2FC**,Number=.,Type=Float,Description="Log2 Fold Change">
##INFO=<ID=**GENE**,Number=.,Type=String,Description="Gene name">

The fields in bold are the 'info' ones used by the variants database, along with the default vcf fields.

**Comment by bryce-turner** [comment]
Implemented as of commit 161dcf3, open to suggestions for improvement
