### ISSUE TITLE
modify input value for annotate task

### ISSUE THREAD

**Issue by ChristopheLegendre** [tgen/phoenix#335]
https://github.com/tgen/phoenix/blob/cfa757f9197a9b8afcea307bd06bb40a3bdd0ca7/modules/somatic/manta.jst#L150

please change that referenced line 150 to :
`{{ constants.phoenix.manta_gene_annotation_parallel }}`

This is within the branch v0.5.1

**Comment by bryce-turner** [comment]
Fixed as of commit caf1ecd
