### ISSUE TITLE
Pairoscope - Found Float Value Instead of Integer value for Window Location

### ISSUE THREAD

**Issue by ChristopheLegendre** [tgen/phoenix#363]
In results file with extension `_pairoscope_igtx_calls.txt`, some values in columns `genename_MAXWINDOWLOCATION` and `genename_NEXTWINDOWLOCATION` are sometimes float number. 

A window location should be represented by an integer.

Could it be possible to convert the Float value to an integer?

**Comment by PedalheadPHX** [comment]
If you make the update I'll accept the pull request, I hate it also, but was to lazy to sort out how to get the integer value as it ends up being #.5 all the time since the calculation is stop-start/2.  Be nice it was the first python code I wrote
