### ISSUE TITLE
Complications with multiple libraries for the same sample

### ISSUE THREAD

**Issue by bryce-turner** [tgen/phoenix#381]
This will likely be a more widespread issue, but we currently are configured to support only a single library per sample. Many of our if blocks check if the libraryCount == 1 but we don't have a case for if libraryCount is greater than 1. Here is an example:
https://github.com/tgen/phoenix/blob/815c0ced685abd096e559bf902b3d81e6cf832ac/modules/qc/bam_qc_rna.jst#L60-L68

The solution I used on the Coyote side is the following:
```jinja2
    if [ -f "{{ rna_metrics }}.pdf" ]; then
    {% if libraryCount == 1 %}
      pdfseparate -f 3 "{{ rna_metrics }}.pdf" {{ rna_metrics }}%d.pdf
      mv {{ rna_metrics }}3.pdf {{ results_dir }}/{{ sample.name }}_{{ sample_lb }}.{{ aligner }}.bam.rna_metrics.pdf
    {% elif bam_level is sameas false or sample.gltype == 'singlecellrna' %}
      pdfseparate -f 3 "{{ rna_metrics }}.pdf" {{ rna_metrics }}%d.pdf
      mv {{ rna_metrics }}3.pdf {{ rna_metrics }}.pdf
    {% elif libraryCount > 1 %}
        pdfseparate -f 3 "{{ rna_metrics }}.pdf" {{ rna_metrics }}%d.pdf
        pdfunite \
          {% for library in range(3, libraryCount + 2) %}
          {{ rna_metrics }}{{ library }}.pdf \
          {% endfor %}
          {{ rna_metrics }}.pdf
    {% endif %}
    fi
```

**Comment by awchrist** [comment]
What error are you getting? We do not want to do the pdf separate on bams that have more than one library by design.

**Comment by bryce-turner** [comment]
Closing this issue after internal discussions. We do not want to split the pdf if we have multiple libraries. Additionally, we moved the if statement to the contained within the jinja syntax such that it does not get rendered if it is not needed.
