### ISSUE TITLE
stats2json - gc_bias_summary_metrics will fail with multiple libraries

### ISSUE THREAD

**Issue by bryce-turner** [tgen/phoenix#382]
**Traceback error:**
```
Traceback (most recent call last):
      File "/home/tgenjetstream/jetstream_pipelines/phoenix-v1_0_2/required_scripts/samStats2json_deb00a0.py", line 1134, in <module>
        fileTypes[args.filetype]["metrics_cols_to_concat"]
      File "/home/tgenjetstream/jetstream_pipelines/phoenix-v1_0_2/required_scripts/samStats2json_deb00a0.py", line 716, in picard_add_metrics_to_dict
        data_line_read_group_name
    TypeError: cannot unpack non-iterable NoneType object
```

**Input file:**
```
## METRICS CLASS        picard.analysis.GcBiasSummaryMetrics
ACCUMULATION_LEVEL      READS_USED      WINDOW_SIZE     TOTAL_CLUSTERS  ALIGNED_READS   AT_DROPOUT      GC_DROPOUT      GC_NC_0_19      GC_NC_20_39     GC_NC_40_59     GC_NC_60_79     GC_NC_80_100    SAMPLE  LIBRARY READ_GROUP
Sample  ALL     100     126341856       251590369       26.979567       0.000288        0.109301        0.455733        1.251647        4.031913        1.510758        GM12878_CORIELL_p8_CL_Whole_C2
Library ALL     100     75274323        149925094       27.333809       0.000143        0.104336        0.449127        1.253793        4.075513        1.569659                L06397
Library ALL     100     51067533        101665275       26.457168       0.00077 0.116624        0.465475        1.248483        3.967617        1.423897                L06401
```

**Code block throwing the error:**
https://github.com/tgen/phoenix/blob/815c0ced685abd096e559bf902b3d81e6cf832ac/required_scripts/samStats2json_deb00a0.py#L673-L717

**My thoughts:**
From what I can gather, this is failing because we are expecting the third row to be at the read group level. However, we do not see this same error when running insert size metrics, which appears to be running very similar code/options.

**Comment by bryce-turner** [comment]
After some experimentation I have found that adding the sample name to the summary_metrics.json allows the json to be generated. This json matches the expected pattern we have from when we have a single library.

This is something that was initially noted by @PedalheadPHX 
> ```
> insert metrics the rows end with
> Sample
> Sample <tab> Library
> Sample <tab> Library
> 
> BUT GC metrics is
> Sample <tab> (BlankLibary)
> (BlankSample) <tab> Library
> (BlankSample) <tab> Library
> ```

**Comment by PedalheadPHX** [comment]
so an inconsistency in the picard output, does this then need a little pre-processing script or an update in stats2json that handles this input in a specific way?

**Comment by bryce-turner** [comment]
I'm thinking a pre-processing script would suffice, we need one for renaming the chromosomes anyway. What I'm not clear on yet is why this inconsistency does not effect the files with only a single library. I'm thinking it's some immediate "parent" relations. Will test with making the third line a read group line.
