### ISSUE TITLE
New Region To Exclude for Pairoscope WGS

### ISSUE THREAD

**Issue by ChristopheLegendre** [tgen/phoenix#388]
A region we have seen in both Exome and WGS/WGL samples that should be added to the exclusion list is:
`chr8:143,243,200-143,244,000` in MAFA region. 

We also might have to extend the one we already have:
from `chr8:143,844,450-143,844,750` to `chr8:143,844,450-143,844,760`

**Comment by PedalheadPHX** [comment]
Fixed in the tumorOnly workflows for high coverage capture calling but needs to be fixed for the main version
