### ISSUE TITLE
STAR alignment Updates

### ISSUE THREAD

**Issue by PedalheadPHX** [tgen/phoenix#392]
https://github.com/tgen/phoenix/blob/815c0ced685abd096e559bf902b3d81e6cf832ac/modules/rna/star_quant.jst#L174-L175

These outputs need to be defined as outputs.

ALSO,

We should mv the STAR log to stats so those can be extract.

**Comment by bryce-turner** [comment]
Would we like to rename the log file you mentioned? It currently is named as {{ sample.name }}.Log.final.out. Also here is a the head of the file I currently have:
```
                                 Started job on |	Dec 08 15:20:42
                             Started mapping on |	Dec 08 15:48:45
                                    Finished on |	Dec 08 20:44:21
       Mapping speed, Million of reads per hour |	22.36

                          Number of input reads |	110166404
                      Average input read length |	166
                                    UNIQUE READS:
                   Uniquely mapped reads number |	81476959
                        Uniquely mapped reads % |	73.96%
```

**Comment by PedalheadPHX** [comment]
I'd make it clear it originates from STAR, so maybe {{sample.name}}_star.Log.final.out

I was going to suggest a bit different name but I think MultiQC will pick these files up and I suspect it does by the common extension
